services:
  meilisearch:
    image: getmeili/meilisearch:v1.0
    ports:
      - 7700:7700
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
  redis:
    image: redis:7
    ports:
      - 6379:6379
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
  dgraph:
    image: dgraph/standalone:v21.03.0
    ports:
      - 5080:5080
      - 8080:8080
      - 9080:9080
    volumes:
      - dgraph:/dgraph
volumes:
  dgraph:
  meilisearch:
